title: Look Into My Realm
description: Gaming, Tech, and Adventures from the void - by GAM3RGAWD
author: GAM3RGAWD
url: https://vitalnexus.github.io
baseurl: /blog

# Jekyll settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Asset settings
sass:
  sass_dir: assets/css
  style: compressed

# Build settings
encoding: utf-8
exclude:
  - .gitignore
  - README*.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .DS_Store
  - Guides

# Permalink settings
permalink: /:categories/:title/

# Post defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "GAM3RGAWD"
      tags: []

# Categories
category_list:
  - reviews
  - thoughts
  - technology
  - gaming
  - space-travel
